/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-18 at 06:35:09 UTC 
 * Modify at your own risk.
 */

package com.appspot.btp_app.shopapi.model;

/**
 * Model definition for Shop.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the shopapi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Shop extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String number;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String password;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String shopAddress;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String shopDetails;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String shopName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String shopNumber;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public Shop setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNumber() {
    return number;
  }

  /**
   * @param number number or {@code null} for none
   */
  public Shop setNumber(java.lang.String number) {
    this.number = number;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPassword() {
    return password;
  }

  /**
   * @param password password or {@code null} for none
   */
  public Shop setPassword(java.lang.String password) {
    this.password = password;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getShopAddress() {
    return shopAddress;
  }

  /**
   * @param shopAddress shopAddress or {@code null} for none
   */
  public Shop setShopAddress(java.lang.String shopAddress) {
    this.shopAddress = shopAddress;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getShopDetails() {
    return shopDetails;
  }

  /**
   * @param shopDetails shopDetails or {@code null} for none
   */
  public Shop setShopDetails(java.lang.String shopDetails) {
    this.shopDetails = shopDetails;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getShopName() {
    return shopName;
  }

  /**
   * @param shopName shopName or {@code null} for none
   */
  public Shop setShopName(java.lang.String shopName) {
    this.shopName = shopName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getShopNumber() {
    return shopNumber;
  }

  /**
   * @param shopNumber shopNumber or {@code null} for none
   */
  public Shop setShopNumber(java.lang.String shopNumber) {
    this.shopNumber = shopNumber;
    return this;
  }

  @Override
  public Shop set(String fieldName, Object value) {
    return (Shop) super.set(fieldName, value);
  }

  @Override
  public Shop clone() {
    return (Shop) super.clone();
  }

}
