/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-18 at 06:35:09 UTC 
 * Modify at your own risk.
 */

package com.appspot.btp_app.shopapi;

/**
 * Service definition for Shopapi (v1).
 *
 * <p>
 * cshopapi
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ShopapiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Shopapi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the shopapi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://btp-app.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "shopapi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Shopapi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Shopapi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "deleteShop".
   *
   * This request holds the parameters needed by the shopapi server.  After setting any optional
   * parameters, call the {@link DeleteShop#execute()} method to invoke the remote operation.
   *
   * @param no
   * @return the request
   */
  public DeleteShop deleteShop(java.lang.String no) throws java.io.IOException {
    DeleteShop result = new DeleteShop(no);
    initialize(result);
    return result;
  }

  public class DeleteShop extends ShopapiRequest<Void> {

    private static final String REST_PATH = "shop/{no}";

    /**
     * Create a request for the method "deleteShop".
     *
     * This request holds the parameters needed by the the shopapi server.  After setting any optional
     * parameters, call the {@link DeleteShop#execute()} method to invoke the remote operation. <p>
     * {@link
     * DeleteShop#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param no
     * @since 1.13
     */
    protected DeleteShop(java.lang.String no) {
      super(Shopapi.this, "DELETE", REST_PATH, null, Void.class);
      this.no = com.google.api.client.util.Preconditions.checkNotNull(no, "Required parameter no must be specified.");
    }

    @Override
    public DeleteShop setAlt(java.lang.String alt) {
      return (DeleteShop) super.setAlt(alt);
    }

    @Override
    public DeleteShop setFields(java.lang.String fields) {
      return (DeleteShop) super.setFields(fields);
    }

    @Override
    public DeleteShop setKey(java.lang.String key) {
      return (DeleteShop) super.setKey(key);
    }

    @Override
    public DeleteShop setOauthToken(java.lang.String oauthToken) {
      return (DeleteShop) super.setOauthToken(oauthToken);
    }

    @Override
    public DeleteShop setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (DeleteShop) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public DeleteShop setQuotaUser(java.lang.String quotaUser) {
      return (DeleteShop) super.setQuotaUser(quotaUser);
    }

    @Override
    public DeleteShop setUserIp(java.lang.String userIp) {
      return (DeleteShop) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String no;

    /**

     */
    public java.lang.String getNo() {
      return no;
    }

    public DeleteShop setNo(java.lang.String no) {
      this.no = no;
      return this;
    }

    @Override
    public DeleteShop set(String parameterName, Object value) {
      return (DeleteShop) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getShop".
   *
   * This request holds the parameters needed by the shopapi server.  After setting any optional
   * parameters, call the {@link GetShop#execute()} method to invoke the remote operation.
   *
   * @param no
   * @return the request
   */
  public GetShop getShop(java.lang.String no) throws java.io.IOException {
    GetShop result = new GetShop(no);
    initialize(result);
    return result;
  }

  public class GetShop extends ShopapiRequest<com.appspot.btp_app.shopapi.model.Shop> {

    private static final String REST_PATH = "shop/{no}";

    /**
     * Create a request for the method "getShop".
     *
     * This request holds the parameters needed by the the shopapi server.  After setting any optional
     * parameters, call the {@link GetShop#execute()} method to invoke the remote operation. <p>
     * {@link
     * GetShop#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param no
     * @since 1.13
     */
    protected GetShop(java.lang.String no) {
      super(Shopapi.this, "GET", REST_PATH, null, com.appspot.btp_app.shopapi.model.Shop.class);
      this.no = com.google.api.client.util.Preconditions.checkNotNull(no, "Required parameter no must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetShop setAlt(java.lang.String alt) {
      return (GetShop) super.setAlt(alt);
    }

    @Override
    public GetShop setFields(java.lang.String fields) {
      return (GetShop) super.setFields(fields);
    }

    @Override
    public GetShop setKey(java.lang.String key) {
      return (GetShop) super.setKey(key);
    }

    @Override
    public GetShop setOauthToken(java.lang.String oauthToken) {
      return (GetShop) super.setOauthToken(oauthToken);
    }

    @Override
    public GetShop setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetShop) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetShop setQuotaUser(java.lang.String quotaUser) {
      return (GetShop) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetShop setUserIp(java.lang.String userIp) {
      return (GetShop) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String no;

    /**

     */
    public java.lang.String getNo() {
      return no;
    }

    public GetShop setNo(java.lang.String no) {
      this.no = no;
      return this;
    }

    @Override
    public GetShop set(String parameterName, Object value) {
      return (GetShop) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertShop".
   *
   * This request holds the parameters needed by the shopapi server.  After setting any optional
   * parameters, call the {@link InsertShop#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.btp_app.shopapi.model.Shop}
   * @return the request
   */
  public InsertShop insertShop(com.appspot.btp_app.shopapi.model.Shop content) throws java.io.IOException {
    InsertShop result = new InsertShop(content);
    initialize(result);
    return result;
  }

  public class InsertShop extends ShopapiRequest<com.appspot.btp_app.shopapi.model.Shop> {

    private static final String REST_PATH = "shop";

    /**
     * Create a request for the method "insertShop".
     *
     * This request holds the parameters needed by the the shopapi server.  After setting any optional
     * parameters, call the {@link InsertShop#execute()} method to invoke the remote operation. <p>
     * {@link
     * InsertShop#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.btp_app.shopapi.model.Shop}
     * @since 1.13
     */
    protected InsertShop(com.appspot.btp_app.shopapi.model.Shop content) {
      super(Shopapi.this, "POST", REST_PATH, content, com.appspot.btp_app.shopapi.model.Shop.class);
    }

    @Override
    public InsertShop setAlt(java.lang.String alt) {
      return (InsertShop) super.setAlt(alt);
    }

    @Override
    public InsertShop setFields(java.lang.String fields) {
      return (InsertShop) super.setFields(fields);
    }

    @Override
    public InsertShop setKey(java.lang.String key) {
      return (InsertShop) super.setKey(key);
    }

    @Override
    public InsertShop setOauthToken(java.lang.String oauthToken) {
      return (InsertShop) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertShop setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertShop) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertShop setQuotaUser(java.lang.String quotaUser) {
      return (InsertShop) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertShop setUserIp(java.lang.String userIp) {
      return (InsertShop) super.setUserIp(userIp);
    }

    @Override
    public InsertShop set(String parameterName, Object value) {
      return (InsertShop) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateShop".
   *
   * This request holds the parameters needed by the shopapi server.  After setting any optional
   * parameters, call the {@link UpdateShop#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.btp_app.shopapi.model.Shop}
   * @return the request
   */
  public UpdateShop updateShop(com.appspot.btp_app.shopapi.model.Shop content) throws java.io.IOException {
    UpdateShop result = new UpdateShop(content);
    initialize(result);
    return result;
  }

  public class UpdateShop extends ShopapiRequest<com.appspot.btp_app.shopapi.model.Shop> {

    private static final String REST_PATH = "shop";

    /**
     * Create a request for the method "updateShop".
     *
     * This request holds the parameters needed by the the shopapi server.  After setting any optional
     * parameters, call the {@link UpdateShop#execute()} method to invoke the remote operation. <p>
     * {@link
     * UpdateShop#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.btp_app.shopapi.model.Shop}
     * @since 1.13
     */
    protected UpdateShop(com.appspot.btp_app.shopapi.model.Shop content) {
      super(Shopapi.this, "PUT", REST_PATH, content, com.appspot.btp_app.shopapi.model.Shop.class);
    }

    @Override
    public UpdateShop setAlt(java.lang.String alt) {
      return (UpdateShop) super.setAlt(alt);
    }

    @Override
    public UpdateShop setFields(java.lang.String fields) {
      return (UpdateShop) super.setFields(fields);
    }

    @Override
    public UpdateShop setKey(java.lang.String key) {
      return (UpdateShop) super.setKey(key);
    }

    @Override
    public UpdateShop setOauthToken(java.lang.String oauthToken) {
      return (UpdateShop) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateShop setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateShop) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateShop setQuotaUser(java.lang.String quotaUser) {
      return (UpdateShop) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateShop setUserIp(java.lang.String userIp) {
      return (UpdateShop) super.setUserIp(userIp);
    }

    @Override
    public UpdateShop set(String parameterName, Object value) {
      return (UpdateShop) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Shopapi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Shopapi}. */
    @Override
    public Shopapi build() {
      return new Shopapi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ShopapiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setShopapiRequestInitializer(
        ShopapiRequestInitializer shopapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(shopapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
